accounts/urls.py
from django.urls import path
from .views import signup, employee_login, logout_view

app_name = 'accounts'

urlpatterns = [

    path('signup/', signup, name='signup'),
    path('login/', employee_login, name='login'),
    path('logout/', logout_view, name='logout'),


]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from jobs.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [

    path('contact/', contact, name='contact'),
    path('about/', about_us, name='about'),
    path('service/', service, name='service'),
    path('job-post/', job_post, name='job-post'),
    path('job-listing/', job_listing, name='job-listing'),
    path('job-single/<int:id>/', job_single, name='job-single'),
    path('search/', SearchView.as_view(), name='search'),
    path('apply/', apply_job, name='apply'),



]

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()


class EmployeeRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=10)
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")
    email = forms.EmailField(label='Email address')
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [

            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'confirm_password',

        ]

    def __init__(self, *args, **kwargs):
        super(EmployeeRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'Enter a valid e-mail'


class EmployeeLoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(EmployeeLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(EmployeeLoginForm, self).clean(*args, **kwargs)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, get_user_model, login, logout
from .forms import EmployeeRegistrationForm, EmployeeLoginForm


def signup(request):
    next = request.GET.get('next')
    form = EmployeeRegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('accounts:login')

    context = {
        'form': form,
    }

    return render(request, "accounts/employee_signup.html", context)


def employee_login(request):
    next = request.GET.get('next')
    form = EmployeeLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                request.session.set_expiry(420)
                login(request, user)
                return redirect('/')
    context = {
        'form': form
    }
    return render(request, "accounts/login.html", context)


def logout_view(request):
    logout(request)
    return redirect('accounts:login')

templates/accounts/employee_signup.html
{% extends 'base.html' %}

{% load bootstrap %}
{% load static %}

{% block content %}
    <section class="home-section section-hero inner-page overlay bg-image"
             style="background-image: url('images/hero_1.jpg');" id="home-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="mb-5 text-center">

                        <h2 class="text-white font-weight-bold">Not our registered yet?</h2>
                        <p>If you have any questions, please feel free to contact us,
                            our customer service center is working for you 24/7.</p>

                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="site-section" id="next-section">
        <div class="container">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <center><h1 class="lead">Sign Up</h1></center>
            </div>
            <div class="row">

                <div class="col-lg-6 mb-5 mb-lg-0">
                    <form action="/accounts/signup/" method="POST">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Sign Up" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                </div>

                <div class="col-lg-5 ml-auto">
                    <div class="p-4 mb-3 bg-white">

                        <img src="{% static 'images/sq_img_3.jpg' %}" alt="Image" class="img-fluid mb-4 rounded">

                    </div>
                </div>

            </div>
        </div>
    </section>


{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}
    <section class="home-section section-hero inner-page overlay bg-image"
             style="background-image: url('images/hero_1.jpg');" id="home-section">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12">
                    <div class="mb-5 text-center">

                        <h2 class="text-white font-weight-bold">LOGIN</h2>


                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="site-section" id="next-section">
        <div class="container">
            <div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <p>Already have your account?</p>
                    <form action="" method="POST">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Login" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                </div>

            </div>
        </div>
    </section>
    <section class="py-5 bg-image overlay-primary fixed overlay">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-8">
                    <h2 class="text-white">Looking For A Job?</h2>
                    <p class="mb-0 text-white lead">Lorem ipsum dolor sit amet consectetur adipisicing elit tempora
                        adipisci
                        impedit.</p>
                    </p>
                </div>
                <div class="col-md-3 ml-auto">
                    <a href="{% url 'accounts:signup' %}" class="btn btn-warning btn-block btn-lg">Sign Up</a>
                </div>
            </div>
        </div>
    </section>


{% endblock %}