accounts/urls.py
from django.urls import path
from .views import signup, employee_login, logout_view

app_name = 'accounts'

urlpatterns = [

    path('signup/', signup, name='signup'),
    path('login/', employee_login, name='login'),
    path('logout/', logout_view, name='logout'),


]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from jobs.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [

    path('contact/', contact, name='contact'),
    path('about/', about_us, name='about'),
    path('service/', service, name='service'),
    path('job-post/', job_post, name='job-post'),
    path('job-listing/', job_listing, name='job-listing'),
    path('job-single/<int:id>/', job_single, name='job-single'),
    path('search/', SearchView.as_view(), name='search'),
    path('apply/', apply_job, name='apply'),



]

templates/base.html
{% load static %}


<html lang="en">
<head>
    <title>Careers </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}


</head>
<body id="top">


<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}




    <footer class="site-footer">


        <div class="container">
            <div class="row mb-5">
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Search Trending</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Graphic Design</a></li>
                        <li><a href="#">Web Developers</a></li>
                        <li><a href="#">Python</a></li>
                        <li><a href="#">HTML5</a></li>
                        <li><a href="#">CSS3</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Company</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Career</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Resources</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Support</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Support</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Terms of Service</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Contact Us</h3>
                    <div class="footer-social">
                        <a href="#"><span class="icon-facebook"></span></a>
                        <a href="#"><span class="icon-twitter"></span></a>
                        <a href="#"><span class="icon-instagram"></span></a>
                        <a href="#"><span class="icon-linkedin"></span></a>
                    </div>
                </div>
            </div>

            <div class="row text-center">
                <div class="col-12">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script>
                        <i
                                class="icon-heart-o" aria-hidden="true"></i> by <a href="om" target="_blank">Careers</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>

</div>

<!-- SCRIPTS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/stickyfill.min.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>

<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/custom.js' %}"></script>
{% block javascripts %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <!-- HOME -->
    <section class="home-section section-hero overlay bg-image"  style="background-image: url('{% static 'images/hero_1.jpg' %}');" id="home-section">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
              <h1 class="text-white font-weight-bold">A Powerful Career Website </h1>
              <p>Find your dream jobs in our powerful career website </p>
            </div>
            <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="search-jobs-form">
              <div class="row mb-5">
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                   <input type="text"  id="title" name="title" class="form-control form-control-lg" placeholder=" Software Engineer ... ">
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                   <input    type="text" id="job_location" name="job_location" class="form-control form-control-lg" placeholder="Dhaka,Bangladesh">
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <select id="employment_status" name="employment_status" class="form-control">
                    <option>Part Time</option>
                    <option>Full Time</option>
                    <option>Freelance</option>
                  </select>
                </div>


                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>


    </section>

    <section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('images/hero_1.jpg');">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2 text-white">Careers Statistics</h2>
            <p class="lead text-white"></p>
          </div>
        </div>
        <div class="row pb-0 block__19738 section-counter">

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ candidates }}">0</strong>
            </div>
            <span class="caption">Candidates</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ job_qs }}"> 0 </strong>
            </div>
            <span class="caption"> Jobs Posted</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="">0</strong>
            </div>
            <span class="caption">Jobs Filled</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="{{ company_name }}">0</strong>
            </div>
            <span class="caption">Companies</span>
          </div>


        </div>
      </div>
    </section>




    <section class="site-section">
     <div class="container">



        <div class="mb-5">
             {% for q in query %}

          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <div class="col-md-2">
              <a href="#"><img src="{% static 'images/featured-listing-1.jpg' %}" alt="Image" class="img-fluid"></a>
            </div>
            <div class="col-md-4">
              <span class="badge badge-primary px-2 py-1 mb-3">

                    {{ q.employment_status }}

              </span>
              <h2><a href="{% url 'jobs:job-single' q.id %}">{{ q.title }}</a> </h2>
              <p class="meta">Publisher: <strong>{{ q.user.first_name }} {{ q.user.last_name }}</strong> In: <strong>{{ q.category }}</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>{{ q.job_location }}</h3>
              <span class="meta"></span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">{{ q.Salary }}</strong>
            </div>
          </div>

{% endfor %}
        </div>



        <div class="row pagination-wrap">

          <div class="col-md-6 text-center text-md-left">
            <div class="custom-pagination ml-auto">
              {% if query.has_previous %}
              <a  href="?page={{ query.previous_page_number }}" class="prev">Previous</a>
              {% endif %}
              <div class="d-inline-block">
                Page <a href="#" class="active">{{ query.number }}</a> of  {{ query.paginator.num_pages }}


              </div>
              {% if query.has_next %}
              <a href="?page={{ query.next_page_number }}" class="next">Next</a>
               {% endif %}
            </div>
          </div>
        </div>

      </div>
    </section>



    <section class="bg-light pt-5 testimony-full">

        <div class="owl-carousel single-carousel">


          <div class="container">
            <div class="row">
              <div class="col-lg-6 mx-auto">
                <img class="img-fluid mx-auto" src="{% static 'images/person_1.jpg' %}" alt="Image">
                <blockquote>
                  <p>&ldquo;Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae.&rdquo;</p>
                  <p><cite> &mdash; Richard Anderson</cite></p>
                </blockquote>
              </div>
            </div>
          </div>

          <div class="container">
            <div class="row">
              <div class="col-lg-6 mx-auto">
                <img class="img-fluid mx-auto" src="{% static 'images/person_2.jpg' %}" alt="Image">
                <blockquote>
                  <p>&ldquo;Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae.&rdquo;</p>
                  <p><cite> &mdash; Chris Peters</cite></p>
                </blockquote>
              </div>
            </div>
          </div>

      </div>

    </section>




{% endblock %}

templates/navbar.html
{% load static %}



<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="{% url 'home' %}">Careers</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="{% url 'home' %}" class="nav-link active">Home</a></li>
          <li><a href="{% url 'jobs:job-listing' %}">Job Listings</a></li>
          <li><a href="{% url 'jobs:about' %}">About</a></li>
          <li><a href="{% url 'jobs:contact' %}">Contact</a></li>
             <li><a href="{% url 'jobs:service' %}"> Services</a></li>


          <li class="d-lg-none"><a href="#">Contact Us</a></li>
        </ul>
      </nav>
{% if user.is_authenticated %}
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">


          <ul class="nav nav-tabs">

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="True" aria-expanded="false">
      {{request.user.first_name}} {{request.user.last_name}}</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>

    </div>
  </li>


</ul>




        </div>
      </div>



{% endif %}
    </div>
  </div>
    </header>