job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from jobs.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [

    path('contact/', contact, name='contact'),
    path('about/', about_us, name='about'),
    path('service/', service, name='service'),
    path('job-post/', job_post, name='job-post'),
    path('job-listing/', job_listing, name='job-listing'),
    path('job-single/<int:id>/', job_single, name='job-single'),
    path('search/', SearchView.as_view(), name='search'),
    path('apply/', apply_job, name='apply'),



]

jobs/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class Contact(models.Model):
    first_name = models.CharField(max_length=20, null=True, blank=True)
    last_name = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField()
    subject = models.CharField(max_length=20, null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.first_name

JOB_TYPE = (
    ('Part Time', 'Part Time'),
    ('Full Time', 'Full Time'),
    ('Freelance', 'Freelancer'),
)

CATEGORY = (
    ('Web Design', 'Web Design'),
    ('Graphic Design', 'Graphic Design'),
    ('Web Developing', 'Web Developing'),
    ('Software Engineering', 'Software Engineering'),
    ('HR', 'HR'),
    ('Marketing', 'Marketing'),
)

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Any', 'Any'),
)

class JobListing(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    title = models.CharField(max_length=100)
    company_name = models.CharField(max_length=200)
    employment_status = models.CharField(choices=JOB_TYPE, max_length=10)
    vacancy = models.CharField(max_length=10, null=True)
    gender = models.CharField(choices=GENDER, max_length=30, null=True)
    category = models.CharField(choices=CATEGORY, max_length=30)
    description = models.TextField()
    responsibilities = models.TextField()
    experience = models.CharField(max_length=100)
    job_location = models.CharField(max_length=120)
    Salary = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(blank=True, upload_to='media', null=True)
    application_deadline = models.DateTimeField()
    published_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("jobs:job-single", args=[self.id])


class ApplyJob(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    file = models.FileField(null=True)

    def __str__(self):
        return self.name

jobs/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['Email'].widget.attrs['placeholder'] = 'Enter a valid E-mail'

    class Meta:
        model = Contact
        fields = [
            'first_name',
            'last_name',
            # 'Email',
            'subject',
            'message'
        ]


class JobListingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(JobListingForm, self).__init__(*args, **kwargs)
        self.fields['job_location'].widget.attrs['placeholder'] = 'Dhaka,Bangladesh'
        self.fields['Salary'].widget.attrs['placeholder'] = '60k-80k BDT, 4k-5k USD, Negotiable'
        self.fields['title'].widget.attrs['placeholder'] = 'Software Engineer, Web Designer'
        self.fields['application_deadline'].widget.attrs['placeholder'] = '2020-12-27'

    class Meta:
        model = JobListing
        exclude = ('user', 'image')
        labels = {
            "job_location": "Job Location",
            "published_on": "Publish Date"
        }


class JobApplyForm(forms.ModelForm):
    class Meta:
        model = ApplyJob
        fields = '__all__'
        labels = {
            "file": "CV (pdf format)",
            "name": "Full Name"

        }

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .forms import ContactForm, JobListingForm, JobApplyForm
from .models import *
from django.template.loader import get_template
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.views.generic import ListView


def home(request):
    qs = JobListing.objects.all()
    jobs = JobListing.objects.all().count()
    user = User.objects.all().count()
    company_name = JobListing.objects.filter(company_name__startswith='P').count()
    paginator = Paginator(qs, 5)  # Show 5 jobs per page
    page = request.GET.get('page')
    try:
        qs = paginator.page(page)
    except PageNotAnInteger:
        qs = paginator.page(1)
    except EmptyPage:
        qs = paginator.page(paginator.num_pages)

    context = {
        'query': qs,
        'job_qs': jobs,
        'company_name': company_name,
        'candidates': user
    }
    return render(request, "home.html", context)


def about_us(request):
    return render(request, "jobs/about_us.html", {})


def service(request):
    return render(request, "jobs/services.html", {})


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        instance.save()
        return redirect('/')
    context = {
        'form': form
    }
    return render(request, "jobs/contact.html", context)


@login_required
def job_listing(request):
    query = JobListing.objects.all().count()

    qs = JobListing.objects.all().order_by('-published_on')
    paginator = Paginator(qs, 3)  # Show 3 jobs per page
    page = request.GET.get('page')
    try:
        qs = paginator.page(page)
    except PageNotAnInteger:
        qs = paginator.page(1)
    except EmptyPage:
        qs = paginator.page(paginator.num_pages)

    context = {
        'query': qs,
        'job_qs': query

    }
    return render(request, "jobs/job_listing.html", context)


@login_required
def job_post(request):
    form = JobListingForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        instance.save()
        return redirect('/jobs/job-listing/')
    context = {
        'form': form,

    }
    return render(request, "jobs/job_post.html", context)


def job_single(request, id):
    job_query = get_object_or_404(JobListing, id=id)

    context = {
        'q': job_query,
    }
    return render(request, "jobs/job_single.html", context)


@login_required
def apply_job(request):
    form = JobApplyForm(request.POST or None, request.FILES)
    if form.is_valid():
        instance = form.save()
        instance.save()
        return redirect('/')
    context = {
        'form': form,

    }
    return render(request, "jobs/job_apply.html", context)


class SearchView(ListView):
    model = JobListing
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(title__contains=self.request.GET['title'],
                                         job_location__contains=self.request.GET['job_location'],
                                         employment_status__contains=self.request.GET['employment_status'])

templates/jobs/about_us.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="home-section section-hero inner-page overlay bg-image"
      style="background-image: url('{% static 'images/hero_1.jpg' %}');" id="home-section">
      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
              <h1 class="text-white font-weight-bold">About Us</h1>
              <p>Find your dream jobs in our powerful career website .</p>
            </div>
          </div>
        </div>
      </div>
    </section>


     <section class="site-section pb-0">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <a data-fancybox data-ratio="2" href="https://vimeo.com/317571768" class="block__96788">
              <span class="play-icon"><span class="icon-play"></span></span>
              <img src="{% static 'images/about_1.jpg' %}" alt="Image" class="img-fluid img-shadow">
            </a>
          </div>
          <div class="col-lg-5 ml-auto">
            <h2 class="section-title mb-3">Careers for Your Careers</h2>
            <p class="lead">Eveniet voluptatibus voluptates suscipit minima, cum voluptatum ut dolor, sed facere corporis
              qui, ea quisquam quis odit minus nulla vitae. Sit, voluptatem.</p>
            <p>Ipsum harum assumenda in eum vel eveniet numquam, cumque vero vitae enim cupiditate deserunt eligendi officia
              modi consectetur. Expedita tempora quos nobis earum hic ex asperiores quisquam optio nostrum sit!</p>
          </div>
        </div>
      </div>
    </section>


    <section class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center" data-aos="fade">
            <h2 class="section-title mb-3">Our Team</h2>
          </div>
        </div>

        <div class="row align-items-center block__69944">

          <div class="col-md-6">
            <img src="{% static 'images/person_2.jpg' %}" alt="Image" class="img-fluid mb-4 rounded">

            <h3>John Smith</h3>
            <p class="text-muted">Creative Director</p>
            <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in
              dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel ad
              explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
            <div class="social mt-4">
              <a href="#"><span class="icon-facebook"></span></a>
              <a href="#"><span class="icon-twitter"></span></a>
              <a href="#"><span class="icon-instagram"></span></a>
              <a href="#"><span class="icon-linkedin"></span></a>
            </div>
          </div>


          <div class="col-md-6 order-md-2">
            <img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid mb-4 rounded">


            <h3>Drew Anderson</h3>
            <p class="text-muted">Creative Director</p>
            <p>Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in
              dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae voluptatibus ut? Ex vel ad
              explicabo iure ipsa possimus consectetur neque rem molestiae eligendi velit?.</p>
            <div class="social mt-4">
              <a href="#"><span class="icon-facebook"></span></a>
              <a href="#"><span class="icon-twitter"></span></a>
              <a href="#"><span class="icon-instagram"></span></a>
              <a href="#"><span class="icon-linkedin"></span></a>
            </div>
          </div>


        </div>

    </section>


    <section class="py-5 bg-image overlay-primary fixed overlay" id="next-section"
      style="background-image: url('images/hero_1.jpg');">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2 text-white">JobBoard Site Stats</h2>
            <p class="lead text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita unde officiis
              recusandae sequi excepturi corrupti.</p>
          </div>
        </div>
        <div class="row pb-0 block__19738 section-counter">

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="1930">0</strong>
            </div>
            <span class="caption">Candidates</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="54">0</strong>
            </div>
            <span class="caption">Jobs Posted</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="120">0</strong>
            </div>
            <span class="caption">Jobs Filled</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="550">0</strong>
            </div>
            <span class="caption">Companies</span>
          </div>


        </div>
      </div>
    </section>


{% endblock %}

templates/jobs/contact.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}


{% block content %}
    <section class="home-section section-hero inner-page overlay bg-image"
             style="background-image: url('{% static 'images/hero_1.jpg' %}');" id="home-section">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12">
                    <div class="mb-5 text-center">
                        <h1 class="text-white font-weight-bold">Contact Us</h1>
                        <p>Find your dream jobs in our powerful career website </p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="site-section" id="next-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <form action="/jobs/contact/" method="POST">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Send Message" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                </div>
                <div class="col-lg-5 ml-auto">
                    <div class="p-4 mb-3 bg-white">
                        <p class="mb-0 font-weight-bold">Address</p>
                        <p class="mb-4">33/7, Block D, Mirpur, Dhaka, Bangladesh</p>

                        <p class="mb-0 font-weight-bold">Phone</p>
                        <p class="mb-4"><a href="#">+88 01798128799</a></p>

                        <p class="mb-0 font-weight-bold">Email Address</p>
                        <p class="mb-0"><a href="#">nazmul199512@gmail.com</a></p>

                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

templates/jobs/job_apply.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% load crispy_forms_filters %}
{% block content %}

    <section class="site-section" id="next-section">
        <div class="container">


            <div class="row justify-content-center">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <center><h1 class="lead">Apply for job </h1></center>
                    <form action="" method="POST" class="" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" onclick="myFunction()" value="Submit"
                                       class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                    <script>
                        function myFunction() {
                            alert("Are you applying to this job?");
                        }
                    </script>

                </div>


            </div>

        </div>
    </section>


{% endblock %}

templates/jobs/job_listing.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <section class="home-section section-hero inner-page overlay bg-image"
             style="background-image: url('{% static 'images/hero_1.jpg' %}');"
             id="home-section">

        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12">
                    <div class="mb-5 text-center">
                        <h1 class="text-white font-weight-bold">Job Listings</h1>
                        <p>Find your dream jobs in our powerful career website.</p>
                    </div>
                </div>
            </div>
        </div>


    </section>





    <section class="site-section">
        <div class="container">

            <div class="row mb-5 justify-content-center">
                <div class="col-md-7 text-center">
                    <h2 class="section-title mb-2">{{ job_qs }} Job Listed</h2>

                    <div class="mb-5 text-center">

                        <a href="{% url 'jobs:job-post' %}"
                           class="btn btn-primary border-width-2 d-none d-lg-inline-block">
                      <span class="mr-2 icon-paper-plane">

                      </span>Post a Job</a>


                    </div>


                </div>
            </div>


            <div class="mb-5">
                {% for q in query %}

                    <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
                        <div class="col-md-2">
                            <a href=""><img class="img-fluid" src="{% static 'images/featured-listing-2.jpg' %}"
                                            alt="image"></a>
                        </div>
                        <div class="col-md-4">
              <span class="badge badge-primary px-2 py-1 mb-3">

                    {{ q.employment_status }}

              </span>
                            <h2><a href="{% url 'jobs:job-single' q.id %}">{{ q.title }}</a></h2>

                            In: <strong>{{ q.category }}</strong></p>
                        </div>
                        <div class="col-md-3 text-left">
                            <h3>{{ q.job_location }}</h3>
                            <span class="meta"></span>
                        </div>
                        <div class="col-md-3 text-md-right">
                            <strong class="text-black">{{ q.Salary }}</strong>
                        </div>
                    </div>

                {% endfor %}
            </div>


            <div class="row pagination-wrap">

                <div class="col-md-6 text-center text-md-left">
                    <div class="custom-pagination ml-auto">
                        {% if query.has_previous %}
                            <a href="?page={{ query.previous_page_number }}" class="prev">Previous</a>
                        {% endif %}
                        <div class="d-inline-block">
                            Page <a href="#" class="active">{{ query.number }}</a> of {{ query.paginator.num_pages }}


                        </div>
                        {% if query.has_next %}
                            <a href="?page={{ query.next_page_number }}" class="next">Next</a>
                        {% endif %}
                    </div>
                </div>
            </div>


        </div>
    </section>






{% endblock %}

templates/jobs/job_post.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block content %}

    <section class="site-section" id="next-section">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <center><h1 class="lead">Post a Job</h1></center>
                    <form action="" method="POST" class="">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="POST" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                </div>


            </div>

        </div>
    </section>


{% endblock %}

templates/jobs/job_single.html
{% extends 'base.html' %}


{% load static %}




{% block content %}
    <!-- HOME -->

    <section class="section-hero overlay inner-page bg-image"
             style="background-image: url('{% static 'images/hero_1.jpg' %}');"
             id="home-section">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="text-white font-weight-bold">{{ q.title }}</h1>
                </div>
            </div>
        </div>
    </section>


    <section class="site-section">
        <div class="container">
            <div class="row align-items-center mb-5">
                <div class="col-lg-8 mb-4 mb-lg-0">
                    <div class="d-flex align-items-center">
                        <div class="border p-2 d-inline-block mr-3 rounded">
                            <img src="{% static 'images/featured-listing-2.jpg' %}"
                                 alt="Free Website Template By Free-Template.co">
                        </div>
                        <div>
                            <h2>{{ q.title }}</h2>
                            <div>
                                <span class="ml-0 mr-2 mb-2"><span
                                        class="icon-briefcase mr-2"></span>{{ q.company_name }}</span>
                                <span class="m-2"><span class="icon-room mr-2"></span>{{ q.job_location }}</span>
                                <span class="m-2"><span class="icon-clock-o mr-2"></span><span
                                        class="text-primary"> {{ q.employment_status }}
                      </span></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="row">

                        <div class="col-6">
                            <a href="{% url 'jobs:apply' %}" class="btn btn-block btn-primary btn-md">Apply Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="mb-5">
                        <figure class="mb-5"><img src="{% static 'images/sq_img_3.jpg' %}"
                                                  alt="Free Website Template by Free-Template.co"
                                                  class="img-fluid rounded"></figure>
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span
                                class="icon-align-left mr-3"></span>Job
                            Description</h3>
                        <p>{{ q.description }}</p>
                    </div>
                    <div class="mb-5">
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span
                                class="icon-rocket mr-3"></span>Responsibilities</h3>
                        <ul class="list-unstyled m-0 p-0">
                            <li class="d-flex align-items-start mb-2"><span
                                    class="icon-check_circle mr-2 text-muted"></span><span>{{ q.responsibilities }}</span>
                            </li>

                        </ul>
                    </div>

                    <div class="mb-5">
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-book mr-3"></span>Experience
                        </h3>
                        <ul class="list-unstyled m-0 p-0">
                            <li class="d-flex align-items-start mb-2"><span
                                    class="icon-check_circle mr-2 text-muted"></span><span>{{ q.experience }}</span>
                            </li>

                        </ul>
                    </div>


                </div>
                <div class="col-lg-4">
                    <div class="bg-light p-3 border rounded mb-4">
                        <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Job Summary</h3>
                        <ul class="list-unstyled pl-3 mb-0">
                            <li class="mb-2"><strong class="text-black">Published
                                on:</strong> {{ q.published_on|timesince }} ago
                            </li>
                            <li class="mb-2"><strong class="text-black">Vacancy:</strong> {{ q.vacancy }}</li>
                            <li class="mb-2"><strong class="text-black">Employment
                                Status:</strong> {{ q.employment_status }}</li>
                            <li class="mb-2"><strong class="text-black">Experience:</strong> {{ q.experience }}</li>
                            <li class="mb-2"><strong class="text-black">Job Location:</strong> {{ q.job_location }}</li>
                            <li class="mb-2"><strong class="text-black">Salary:</strong> {{ q.Salary }}</li>
                            <li class="mb-2"><strong class="text-black">Gender:</strong> {{ q.gender }}</li>
                            <li class="mb-2"><strong class="text-black">Application
                                Deadline:</strong> {{ q.application_deadline }}</li>
                        </ul>
                    </div>

                    <div class="bg-light p-3 border rounded">
                        <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Share</h3>
                        <div class="px-3">
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-facebook"></span></a>
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-twitter"></span></a>
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-linkedin"></span></a>
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-pinterest"></span></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>



{% endblock %}

templates/jobs/search.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <!-- HOME -->
    <section class="home-section section-hero overlay bg-image"  style="background-image: url('{% static 'images/hero_1.jpg' %}');" id="home-section">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
                        <h1 class="text-white font-weight-bold"> Find your  job in our  career website</h1>

            </div>
            <form id="job-main-form" method="get" action="#" class="search-jobs-form">
              <div class="row mb-5">
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <input type="text"  id="title" name="title" class="form-control form-control-lg" placeholder=" Software Engineer ... ">
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                   <input    type="text" id="job_location" name="job_location" class="form-control form-control-lg" placeholder="Dhaka,Bangladesh">
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <select id="employment_status" name="employment_status" class="form-control">
                    <option>Part Time</option>
                    <option>Full Time</option>
                    <option>Freelance</option>
                  </select>
                </div>


                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
              </div>
            </form>

          </div>
        </div>



      </div>


    </section>







<section class="site-section">

  <div class="container">

        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">We have found <span class="accent">{{ jobs.count }}</span> jobs</h2>




          </div>
        </div>

         {% for job in jobs %}

        <div class="mb-5">


          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <div class="col-md-2">
              <a  href=""><img class="img-fluid" src="{% static 'images/featured-listing-2.jpg' %}" alt="image" ></a>
            </div>
            <div class="col-md-4">
              <span class="badge badge-primary px-2 py-1 mb-3">

                    {{ job.employment_status }}

              </span>
              <h2><a href="{% url 'jobs:job-single' job.id %}">{{ job.title }}</a> </h2>
              <p class="meta">Publisher: <strong>{{ job.user.first_name }} {{ job.user.last_name }}</strong> In: <strong>{{ job.category }}</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3>{{ job.job_location }}</h3>
              <span class="meta"></span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">{{ job.Salary }}</strong>
            </div>
          </div>

            {% endfor %}
        </div>



      </div>



     </section>







{% endblock %}